### PR TITLE
VoiceRecorder - change default format to MP4

### PR DESCRIPTION
**Pull request by wiertel**
As you can see in the list of commits, the PR includes updating Xamarin.Forms to 5.0, Tizen.Log.Error() logging, and a small change in the app.
In standard 6.0 mobile emulator there is an issue with MetadataExtractor for WAV files. It causes an error popup when the recording is finished and when you start application while there already are some wav recordings. The playback works, but the app cant find the duration of the recording. I've decided to change the app and record MP4 by default. As long as the user sticks to the default everything is working correctly.
I've tried it on 5.5 emulator - the duration is determined correctly, but the playback fails.

### CODE REVIEW

**Comment by sgchoi5** [comment]
I've sent a review-request to Multimedia part for MetadataExtractor problem.

**Comment by hsgwon** [comment]
Dear @wiertel ,
If you can test with latest 6.0 emulator binary(after 6.0 official release version), **it works without any modification** in your app.
(Some fixes are included after 6.0 release)

But, if you can't, you can change the audio codec and its format(Aac, Mp4) to solve the problem.

**Comment by sgchoi5** [comment]
We need to prepare for codes for 3rd part developers with Public Official version. I think... using MP4 is current best solution.

**Review by sgchoi5 — APPROVED** [review]

**Comment by wiertel** [comment]
I can confirm that on new image ([tizen-6.0-unified_20210611.1](http://download.tizen.org/snapshots/tizen/6.0-unified/tizen-6.0-unified_20210611.1/images/emulator/mobile-emulator32-wayland/)) WAV works. Still, we better switch the default format. Application allows changing between MP4, WAV, and OGG (for the OGG there is an message saying that it's not supported).

**Review by hsgwon — APPROVED** [review]

**Pull request merged**
