### PR TITLE
Remastered Wearable\UIControlSample

### PR DESCRIPTION
**Pull request by mmaciola**
Sample Wearable\UIControlSample was fully remastered to show third party developers the usage of basic NUI.Components.
Before fix sample didnt worked. Majority of elements didn't show or was unusable. Despite its name, sample no more used NUI.UIComponents.* but NUI.Components.*.

View before:
UISamplePre
View after:
UISample1

### CODE REVIEW

**Comment by myroot** [comment]
Do not merge before release Tizen.net 8.0

**Comment by myroot** [comment]
Now you can merge into API8 branch, 
We will merge API8 branch into master after release tizen80

**Comment by myroot** [comment]
tizen80 was released

**Review by Seoyeon2Kim — APPROVED** [review]
Looks good to me. ;)
BTW, should we update verified version of this PR again?
The current TizenFX API version is 9

**Review by hyunjushin — APPROVED** [review]

**Pull request merged**
