### PR TITLE
[TV][NUI] Fix TextSample code

### PR DESCRIPTION
**Pull request by pkalota**
Decreased `PointSize` of components.
Initialized buttons with `BackgroundImage ` and `TextColor `

### CODE REVIEW

**Review by Seoyeon2Kim — COMMENTED** [review]
I think this sample is fit for real TV target.
Do you check on TV?

**Comment by pkalota** [comment]
I've checked it only on emulator. I had no idea it is for real TV target.

**Comment by dongsug-song** [comment]
@pkalota 
Hello,
could you check this link ? : https://code.sec.samsung.net/confluence/display/GFX/How+to+use+VD+TV+emulator
you can see how to use tizen TV emulator and also Mobile emulator.
thank you.

**Comment by pkalota** [comment]
@dongsug-song Hello, I'm already using TV and Mobile emulators. Basing on @Seoyeon2Kim comment I will close this PR since it might be smaple for real TV target.

**Pull request closed without merging**
