### PR TITLE
[NUI][View] animation and alignment fixed 

### PR DESCRIPTION
**Pull request by mgrudzinska**
animation cleared if not used,
deprecated events changed to the new ones,
text label properly centered,
button default properties changed

### CODE REVIEW

**Comment by dongsug-song** [comment]
@mgrudzinska 
do you mean you will fix the touch issue later?

**Comment by mgrudzinska** [comment]
@dongsug-song now everything should work ! :)

**Comment by mgrudzinska** [comment]
@dongsug-song ping

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
