### PR TITLE
[NUI][Mobile] Add theming example

### PR DESCRIPTION
**Pull request by mihashco**

### CODE REVIEW

**Comment by rabbitfor** [comment]
Json styling is from DALi so it can not be applied to NUI.Components.
For this reason, a new theme system is about to introduced which enable NUI styleing with XAML, so I think  it's better not to open this sample.

**Comment by mihashco** [comment]
> Json styling is from DALi so it can not be applied to NUI.Components.
> For this reason, a new theme system is about to introduced which enable NUI styling with XAML, so I think it's better not to open this sample.
Hello, thank you for information. I can rewrite this sample using XAML if you want. Please let me know about that.

**Comment by Seoyeon2Kim** [comment]
I'm sorry to say that this PR is not available anymore.
Unfortunately, from Tizen 6.5 (TizenFX API 9), NUI guides to use Tizen.NUI.ThemeManager for styling components, not to use Tizen.NUI.StyleManager.

**Comment by Seoyeon2Kim** [comment]
I'm sorry to say that this PR is not available anymore.
Unfortunately, from Tizen 6.5 (TizenFX API 9), NUI guides to use Tizen.NUI.ThemeManager for styling components, not to use Tizen.NUI.StyleManager. 

@rabbitfor , could you check it one more time?

**Pull request closed without merging**
