### PR TITLE
[Mobile][NUI] Pagination example added - will be linked in the guide

### PR DESCRIPTION
**Pull request by mgrudzinska**
a simple pagination example, that will be added to the guide

### CODE REVIEW

**Comment by Seoyeon2Kim** [comment]
I'll review this PR after updating a guide, like README.md.

**Comment by mgrudzinska** [comment]
README and screenshots are added

**Review by Seoyeon2Kim — APPROVED** [review]
Looks good to me :)

**Comment by dongsug-song** [comment]
Hello,
Thank you for your works done.

please check the links below and you can see SVACE, Comments Ratio checking, spelling checking, and etc are required.

https://code.sec.samsung.net/confluence/display/TNET/C%23+Sample+release+process

please check the guides and upload the results (any format would be OK) here.
all the checker hurdles are resolved, then we can merge this PR.
thank you.

**Pull request merged**
