### PR TITLE
[NUI][CustomLayout] Code cleanup.

### PR DESCRIPTION
**Pull request by mihashco**
Fixes:
1. Fixed invalid dependencies
2. Fixed back key handling on emulator
3. Fixed whitespaces

### CODE REVIEW

**Comment by dongsug-song** [comment]
@mihashco 
Hello,
I couldn't see any introductory page or screen shot which usually shown in README.md.
could you check other sample and add ?
thank you.

**Comment by dongsug-song** [comment]
Hello,
Thank you for your works done.

please check the links below and you can see SVACE, Comments Ratio checking, spelling checking, and etc are required.

https://code.sec.samsung.net/confluence/display/TNET/C%23+Sample+release+process

please check the guides and upload the results (any format would be OK) here.
all the checker hurdles are resolved, then we can merge this PR.
thank you.

**Comment by mihashco** [comment]
> @mihashco
> Hello,
> I couldn't see any introductory page or screen shot which usually shown in README.md.
> could you check other sample and add ?
> thank you.

It was added in previous commit merged some time ago. 
https://github.com/Samsung/Tizen-CSharp-Samples/tree/master/Mobile/NUI_CustomLayout

**Comment by mihashco** [comment]
> Hello,
> Thank you for your works done.
> 
> please check the links below and you can see SVACE, Comments Ratio checking, spelling checking, and etc are required.
> 
> https://code.sec.samsung.net/confluence/display/TNET/C%23+Sample+release+process
> 
> please check the guides and upload the results (any format would be OK) here.
> all the checker hurdles are resolved, then we can merge this PR.
> thank you.

Thanks for support. Could you explain how to count comments ratio? On site you linked above, there is a link to community, but I have no access there.

**Comment by mihashco** [comment]
> > Hello,
> > Thank you for your works done.
> > please check the links below and you can see SVACE, Comments Ratio checking, spelling checking, and etc are required.
> > https://code.sec.samsung.net/confluence/display/TNET/C%23+Sample+release+process
> > please check the guides and upload the results (any format would be OK) here.
> > all the checker hurdles are resolved, then we can merge this PR.
> > thank you.
> 
> Thanks for support. Could you explain how to count comments ratio? On site you linked above, there is a link to community, but I have no access there.

Information was uploaded. Thank you for review

**Pull request merged**
